Pandas is the most popular python library that is used for data analysis. It provides highly optimized performance with back-end source code is purely written in C or Python.

We can analyze data in pandas with:

- Series
- DataFrames

### Series:
Series is one dimensional(1-D) array defined in pandas that can be used to store any data type.

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

In [1]:
import numpy as np
import pandas as pd

In [2]:
my_list = [10 , 20 , 30 , 40]
arr = np.array(my_list)

In [3]:
arr

array([10, 20, 30, 40])

In [4]:
pd.Series(data=my_list)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
labels = ['a' , 'b' , 'c' , 'd']
pd.Series(data = my_list , index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
#converting an array in to series

pd.Series(arr , labels)

a    10
b    20
c    30
d    40
dtype: int64

In [7]:
#converting dictionary to series

d = {'a':10 , 'b':20 , 'c':30 , 'd':40}
pd.Series(data=d)

a    10
b    20
c    30
d    40
dtype: int64

In [8]:
#Series can hold a variety of object types

pd.Series(data=labels)

0    a
1    b
2    c
3    d
dtype: object

In [9]:
ser1 = pd.Series([1 , 2, 3, 4] , index= ['nandu' , 'nani' , 'venky' , 'jaswanth'])
ser2 = pd.Series([1 , 2 , 4 , 6] , index=['nani' , 'chakri' , 'nandu' , 'venky'])

In [10]:
ser1


nandu       1
nani        2
venky       3
jaswanth    4
dtype: int64

In [11]:
ser2

nani      1
chakri    2
nandu     4
venky     6
dtype: int64

In [12]:
ser1['nandu']

1

In [13]:
ser2['nandu']

4

In [14]:
ser1.values

array([1, 2, 3, 4])

In [15]:
ser2.values

array([1, 2, 4, 6])

In [16]:
ser1 + ser2 #common index values are added

chakri      NaN
jaswanth    NaN
nandu       5.0
nani        3.0
venky       9.0
dtype: float64